host: https://esteventester.testrail.io
project: test
username: atharv.esteven@foundtoo.com
key: /2HLUtQj8Lftji0KqynP-tDOf/YIPzEDaDRaPAXU6
title: SmokeTest.xml
run_id: 42
suite_id: 28
file: C:\Users\Hasan Abdullah\IdeaProjects\testng\report_sample\MultiplicationTest.xml
