name: Test PowerShell on Ubuntu
on: push

jobs:
  hasan-test:
    name:  test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Perform a Pester test from the Tests.ps1 file
        shell: pwsh
        run: |
         mvn test -DsuiteXmlFile=Ressources/PlayerRegressionTest.xml

